import multiprocessing
import shutil
import tempfile
from pathlib import Path

# --- Configuration and Constants ---
FFMPEG_PATH = shutil.which("ffmpeg")
FFPROBE_PATH = shutil.which("ffprobe")
CPU_CORES = multiprocessing.cpu_count()
MAX_THREADS = min(CPU_CORES, 16)
CACHE_DIR = Path.home() / ".video_converter_cache"
TEMP_DIR = Path(tempfile.gettempdir()) / "video_converter_temp"
PRESETS_FILE = Path.home() / ".video_converter_presets.json"

# Color correction presets
COLOR_PRESETS = {
    "Normal": {"brightness": 0.0, "contrast": 1.0, "saturation": 1.0, "sharp": 0.0, "blur": 0.0, "gamma": 1.0},
    "Vibrant": {"brightness": 0.02, "contrast": 1.15, "saturation": 1.25, "sharp": 0.5, "blur": 0.0, "gamma": 1.1},
    "Soft": {"brightness": 0.05, "contrast": 0.95, "saturation": 0.9, "sharp": 0.0, "blur": 0.8, "gamma": 1.0},
    "High Contrast": {"brightness": 0.0, "contrast": 1.25, "saturation": 1.1, "sharp": 1.0, "blur": 0.0, "gamma": 1.0},
    "Desaturated": {"brightness": 0.0, "contrast": 1.05, "saturation": 0.7, "sharp": 0.0, "blur": 0.0, "gamma": 1.0},
    "Warm": {"brightness": 0.03, "contrast": 1.05, "saturation": 1.15, "sharp": 0.3, "blur": 0.0, "gamma": 1.05},
    "Cool": {"brightness": -0.02, "contrast": 1.1, "saturation": 1.05, "sharp": 0.4, "blur": 0.0, "gamma": 0.95}
}

# Language translations
translations = {
    "galego": {
        "title": "Video Converter Pro+ (Optimizado)",
        "input_file": "Ficheiro de entrada",
        "output_path": "Ruta de saída",
        "preset_management": "💾 Xestión de Axustes",
        "load_preset": "Cargar axuste gardado",
        "load": "Cargar",
        "delete": "Eliminar",
        "new_preset": "Nome do novo axuste",
        "save": "Gardar Axustes Actuais",
        "main_options": "⚙️ Opcións principais",
        "speed": "Velocidade",
        "quality": "Calidade (CRF/QP)",
        "use_gpu": "Usar GPU (NVIDIA NVENC)",
        "resolution_fps": "📐 Resolución e FPS",
        "scale_enabled": "Activar escalado",
        "scale_factor": "Factor de escalado (%)",
        "fixed_res_enabled": "Recortar a resolución fixa",
        "fixed_res_value": "Resolución (ex., 1280x720)",
        "res_mode": "Modo de resolución",
        "interpolate": "Interpolar (mellor cámara lenta)",
        "custom_fps": "Usar FPS personalizado",
        "fps_value": "FPS obxectivo",
        "rotation": "Rotaci��n (graos)",
        "color_correction": "🎨 Corrección de cor",
        "color_preset": "Predefinición de cor",
        "brightness": "Brillo",
        "contrast": "Contraste",
        "saturation": "Saturación",
        "sharp": "Enfoque",
        "blur": "Desenfoque",
        "gamma": "Gamma",
        "preview_frame_label": "Previsualizar Fotograma",
        "frame_slider_label": "Fotograma",
        "audio_options": "🎵 Opcións de audio",
        "process_audio": "Procesar audio orixinal",
        "preserve_pitch": "Preservar ton",
        "trim_to_video": "Recortar pistas de audio á duración do vídeo orixinal",
        "use_shortest": "Usar duración da pista máis curta",
        "audio_track_1_label": "Track 1 (e.g., music)",
        "audio_track_1": "Subir pista de audio 1",
        "fade_in_1": "Entrada gradual (s)",
        "fade_out_1": "Saída gradual (s)",
        "audio_track_2_label": "Track 2 (e.g., sound effects)",
        "audio_track_2": "Subir pista de audio 2",
        "fade_in_2": "Entrada gradual (s)",
        "fade_out_2": "Saída gradual (s)",
        "mixer": "🎚️ Mesturador de audio",
        "vol_original": "Volume do audio orixinal",
        "vol_track_1": "Volume da pista 1",
        "vol_track_2": "Volume da pista 2",
        "process": "🚀 Procesar vídeo",
        "cancel": "❌ Cancelar Procesamento",
        "quit": "🔴 Pechar Aplicación",
        "result_video": "Vídeo de saída",
        "input_info": "Información do ficheiro de entrada",
        "output_info": "Información do ficheiro de saída",
        "before": "Antes",
        "after": "Despois",
        "warning_no_preset_name": "Por favor, introduce un nome para o axuste.",
        "warning_preset_exists": "O axuste",
        "info_preset_saved": "Axuste gardado:",
        "info_preset_updated": "Axuste actualizado:",
        "info_loading_preset": "Cargando axuste",
        "warning_preset_not_found": "Non se atopou o axuste",
        "warning_no_preset_selected": "Por favor, elixe un axuste para eliminar.",
        "info_preset_deleted": "Axuste",
        "warning_to_delete": "para eliminar.",
        "error_no_input_file": "Por favor, sube un ficheiro primeiro.",
        "error_input_file_not_found": "O ficheiro de entrada",
        "error_extracting_frames": "Erro ao extraer fotogramas",
        "error_no_frames_in_cache": "Non se atoparon fotogramas na caché",
        "error_cannot_determine_frame_dimensions": "Non se puideron determinar as dimensións dos fotogramas na caché",
        "error_invalid_resolution_mode": "Modo de resolución non válido.",
        "error_invalid_resolution_format": "Resolución non válida. Usa: 1920x1080",
        "error_audio_track_not_found": "A pista de audio",
        "error_audio_track_invalid_duration": "A pista de audio",
        "error_ffmpeg": "Erro de FFmpeg",
        "error_video_processing_failed": "O procesamento de vídeo fallou",
        "clear_cache": "Limpar Caché",
        "cache_cleared_message": "Caché borrada con éxito!",
        "cache_hit_message": "Resultado atopado na caché! A operación foi instantánea."
    },
    "english": {
        "title": "Video Converter Pro+ (Optimized)",
        "input_file": "Input File",
        "output_path": "Output Path",
        "preset_management": "💾 Preset Management",
        "load_preset": "Load Saved Preset",
        "load": "Load",
        "delete": "Delete",
        "new_preset": "New Preset Name",
        "save": "Save Current Settings",
        "main_options": "⚙️ Main Options",
        "speed": "Speed",
        "quality": "Quality (CRF/QP)",
        "use_gpu": "Use GPU (NVIDIA NVENC)",
        "resolution_fps": "📐 Resolution and FPS",
        "scale_enabled": "Enable Scaling",
        "scale_factor": "Scaling Factor (%)",
        "fixed_res_enabled": "Crop to Fixed Resolution",
        "fixed_res_value": "Resolution (e.g., 1280x720)",
        "res_mode": "Resolution Mode",
        "interpolate": "Interpolate (better slow motion)",
        "custom_fps": "Use Custom FPS",
        "fps_value": "Target FPS",
        "rotation": "Rotation (degrees)",
        "color_correction": "🎨 Color Correction",
        "color_preset": "Color Preset",
        "brightness": "Brightness",
        "contrast": "Contrast",
        "saturation": "Saturation",
        "sharp": "Sharpness",
        "blur": "Blur",
        "gamma": "Gamma",
        "preview_frame_label": "Preview Frame",
        "frame_slider_label": "Frame",
        "audio_options": "🎵 Audio Options",
        "process_audio": "Process Original Audio",
        "preserve_pitch": "Preserve Pitch",
        "trim_to_video": "Trim Audio Tracks to Video Duration",
        "use_shortest": "Use Shortest Track Duration",
        "audio_track_1_label": "Track 1 (e.g., music)",
        "audio_track_1": "Upload Audio Track 1",
        "fade_in_1": "Fade In (s)",
        "fade_out_1": "Fade Out (s)",
        "audio_track_2_label": "Track 2 (e.g., sound effects)",
        "audio_track_2": "Upload Audio Track 2",
        "fade_in_2": "Fade In (s)",
        "fade_out_2": "Fade Out (s)",
        "mixer": "🎚️ Audio Mixer",
        "vol_original": "Original Audio Volume",
        "vol_track_1": "Track 1 Volume",
        "vol_track_2": "Track 2 Volume",
        "process": "🚀 Process Video",
        "cancel": "❌ Cancel Processing",
        "quit": "🔴 Close Application",
        "result_video": "Output Video",
        "input_info": "Input File Information",
        "output_info": "Output File Information",
        "before": "Before",
        "after": "After",
        "warning_no_preset_name": "Please enter a name for the preset.",
        "warning_preset_exists": "The preset",
        "info_preset_saved": "Preset saved:",
        "info_preset_updated": "Preset updated:",
        "info_loading_preset": "Loading preset",
        "warning_preset_not_found": "Preset not found",
        "warning_no_preset_selected": "Please select a preset to delete.",
        "info_preset_deleted": "Preset",
        "warning_to_delete": "to delete.",
        "error_no_input_file": "Please upload a file first.",
        "error_input_file_not_found": "The input file",
        "error_extracting_frames": "Error extracting frames",
        "error_no_frames_in_cache": "No frames found in cache",
        "error_cannot_determine_frame_dimensions": "Could not determine frame dimensions in cache",
        "error_invalid_resolution_mode": "Invalid resolution mode.",
        "error_invalid_resolution_format": "Invalid resolution format. Use: 1920x1080",
        "error_audio_track_not_found": "The audio track",
        "error_audio_track_invalid_duration": "The audio track",
        "error_ffmpeg": "FFmpeg error",
        "error_video_processing_failed": "Video processing failed",
        "clear_cache": "Clear Cache",
        "cache_cleared_message": "Cache cleared successfully!",
        "cache_hit_message": "Result found in cache! The operation was instantaneous."
    }
}
